mkdir: cannot create directory ‘resultsdump/diverse1’: File exists
mkdir: cannot create directory ‘resultsdump/diverse1/pickles’: File exists
2024-03-27 09:07:27.559443: W external/tsl/tsl/framework/bfc_allocator.cc:296] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.51GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.
Traceback (most recent call last):
  File "/n/holyscratch01/pehlevan_lab/Lab/mletey/ICLexperiments/experiment/remote/smoothsweep/final.py", line 35, in <module>
    state, hist = train(config, data_iter=iter(trainobject), loss='mse', test_every=1000, train_iters=500000, optim=optax.adamw,lr=1e-4)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/holyscratch01/pehlevan_lab/Lab/mletey/ICLexperiments/experiment/remote/smoothsweep/../../../traintheory.py", line 164, in train
    state = create_train_state(init_rng, model, samp_x, optim=optim, **opt_kwargs) # the samp_x data is not used during this initialisation
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/holyscratch01/pehlevan_lab/Lab/mletey/ICLexperiments/experiment/remote/smoothsweep/../../../traintheory.py", line 47, in create_train_state
    params = model.init(rng, dummy_input)['params']
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/holyscratch01/pehlevan_lab/Lab/mletey/ICLexperiments/experiment/remote/smoothsweep/../../../model/transformer.py", line 298, in __call__
    y = TransformerBlock(
        ^^^^^^^^^^^^^^^^^
  File "/n/holyscratch01/pehlevan_lab/Lab/mletey/ICLexperiments/experiment/remote/smoothsweep/../../../model/transformer.py", line 186, in __call__
    x = SingleHeadSelfAttention(self.config)(inputs, decoder_mask, idxs=idxs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/holyscratch01/pehlevan_lab/Lab/mletey/ICLexperiments/experiment/remote/smoothsweep/../../../model/transformer.py", line 109, in __call__
    attn_weights = jnp.einsum('...qd,...kd->...qk', query, key)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home05/mletey/.conda/envs/try4/lib/python3.12/site-packages/jax/_src/numpy/lax_numpy.py", line 3494, in einsum
    return einsum(operands, contractions, precision,  # type: ignore[operator]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home05/mletey/.conda/envs/try4/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 1623817216 bytes.
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
